# -*- coding: utf-8 -*-
"""Avance_proyecto.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aTj1oaZLY9H0X73k2WX80ltAYu8CMWp1
"""

# Commented out IPython magic to ensure Python compatibility.

import pandas as pd
import matplotlib.pyplot as plt
import geopandas as gpd
import numpy as np
# %matplotlib inline
import descartes
import fiona
import shapely
df=pd.read_csv("https://raw.githubusercontent.com/memocantu01/Project1/main/COVID-19_Vaccinations_in_the_United_States_Jurisdiction.csv")



print(df.head())

display(df.head())
# Crear la tabla dinámica con la ubicación, la cantidad de dosis distribuidas y la cantidad de dosis administradas
tabla = df.pivot_table(index='Location', values=['Distributed', 'Administered'], aggfunc='sum')

# Mostrar la tabla
display(tabla)


# Crear la gráfica de barras

ax = tabla.plot(kind='bar', figsize=(15,8))


#Agregar títulos y etiquetas de los ejes"
ax.set_title('Dosis distribuidas y administradas por entidad federativa')
ax.set_xlabel('Entidad ')
ax.set_ylabel('Cantidad de dosis')

# Mostrar la gráfica
plt.show()

# Encontrar el valor máximo de Administered Pfizer por estado
max_administered_pfizer_por_estado = df.groupby('Location')['Administered_Pfizer'].max()

# Mostrar los resultados
print(max_administered_pfizer_por_estado)

# Encontrar el valor mínimo de Administered Pfizer por estado
min_administered_pfizer_por_estado = df.groupby('Location')['Administered_Pfizer'].min()

# Mostrar los resultados
print(min_administered_pfizer_por_estado)

# Cargar el shapefile de los estados de EE.UU. en un objeto GeoDataFrame
#estados = gpd.read_file("https://github.com/memocantu01/Project1/blob/main/cb_2019_us_state_500k.shp")
#estados = gpd.read_file('cb_2019_us_state_500k.shp')
#estados = gpd.read_file('zip://cb_2019_us_state_500k.zip')
#estados.head()
#estados=gpd.read_file("cb_2019_us_state_500k.zip")
# Fusionar los datos de la vacunación con los datos del GeoDataFrame de los estados
estados = estados.merge(df, left_on='NAME', right_on='Location')

# Calcular la media de dosis administradas por estado
media_administradas = estados['Administered'].mean()

estados = estados.set_index('Location')

#Crear una columna para identificar los estados por encima o por debajo de la media
estados['colores'] = 'gray'
estados.loc[estados['Administered'] > media_administradas, 'colores'] = 'green'
estados.loc[estados['Administered'] <= media_administradas, 'colores'] = 'red'


# Crear el mapa y ajustar la escala para que se ajuste a los límites de los EE.UU.


ax = estados.plot(column='colores', legend=True, figsize=(10,5),aspect="equal")
ax.axis('off')
ax.set_xlim([-140,-50])
ax.set_ylim([15, 60])

plt.tight_layout()

# Añadir un título al mapa
ax.set_title('Estados de EE.UU. con la cantidad de dosis administradas de vacunas', fontdict={'fontsize': 20, 'fontweight' : 'bold'})

# Añadir una leyenda personalizada
legend_colors = {'green': 'Por encima de la media', 'red': 'Por debajo de la media'}
patches = [plt.plot([],[], marker='o', ms=10, ls="", mec=None, color=color, 
            label=label)[0]  for color, label in legend_colors.items()]
ax.legend(handles=patches, bbox_to_anchor=(1.05, 1), loc='upper left', borderaxespad=0.)

plt.show()

"""El archivo anterior fue tomado de la organizacion Centers for Disease Control and Prevention.En este documento se puede observar las dosis distrubuidas y administradas en distintos estados de U.S.A.


Los datos presentes en dicho documento pueden tener muchas posibles aplicaciones ,se puede tratar de demostrar la hipotesis de que en aquellos estados con mayores dosis administradas,las muertes por COVID-19 son menores que en aquellos que no.El presente codigo mouestra un mapa con los estados por encima de la media en dosis distrubuidas y administradas en color verde mientras que aquellos por debajo de la media en rojo.


Los datos contenidos en este codigo podrian responder a las siguientes probelmaticas:

¿Que estado tuvo mayor cantidad de  dosis adminstradas entre la poblacion?

¿Que estado tuve la menor?

¿Habra una correlacion entre las dosis adminsitradas y la cantidad de defunciones en dichos estados?

¿Afecta la ideologia politica el porcentaje de vacunacion?

¿Que efectos tuvieron los refuerzos de vacunacion?

¿Que vacuna tuvo mayor efectivad (Pfizer,Moderna,Jonhson,etc)?

Porcentajes de la poblacion vacunados

Gastos en salud publica estatales y dosis distribuidas


Esta informacion seria relevante para el gobierno de U.S.A para ver la efectividad de sus esquemas de vacunacion y sus efectos en la poblacion .Ademas grupos de medicos y cientificos podrian usar la informacion para validar hipotesis sobre las vacunas de Covid-19.

Los probelmas que se presentaron al realizar el codigo fueron usar librerias nuevas como GeoPandas que se usan para visualizar mapas en Pyton ya que nunca antes habia trabajado con ellas.Otro problema que presente fue el de ajustar los mapas ,titulos y leyendas para que sean visualmente atractivos para el lector y pueda se pueda transmitir adecuadamente los datos.








"""

!pip install pandas

!wget https://www2.census.gov/geo/tiger/GENZ2019/shp/cb_2019_us_state_500k.zip

pip install geopandas

pip install numpy

pip install descartes

pip install geopandas

pip install descartes

pip install fiona

!wget https://www2.census.gov/geo/tiger/GENZ2019/shp/cb_2019_us_state_500k.zip

pip install shapely

